echo given tests
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal  5 10 12 18
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal  5 10 12 18
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 12 5 23 9
echo more test
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 17 22 3 14
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 6 20 11 2
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 24 16 7 18
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 4 10 19 1
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 13 8 21 15
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 25 1 9 3
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 16 6 12 22
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 5 23 2 17
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 18 14 1 20
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 11 21 13 8
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 15 24 4 10
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 19 9 17 1
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 7 3 6 16
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 22 12 20 5
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 2 1 14 23
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 10 11 8 21
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 13 15 24 4
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 18 19 1 9
cd /Users/matgib/repos/CS5000/A02 ; /usr/bin/env /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home/bin/java --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/matgib/repos/CS5000/A02/bin BestAppleDeal 7 16 25 22
